version: '2'
services:
  calculate_feasibility:
    image: sitapati/zb-calculate_feasibility
    container_name: calculate_feasibility
    network_mode: "host"
    environment:
       - ZEEBE_BROKER_ADDRESS
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "10"
  communicate:
    image: sitapati/zb-communicate
    container_name: communicate
    network_mode: "host"
    environment:
       - ZEEBE_BROKER_ADDRESS
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "10"
  create_job:
    image: sitapati/zb-create_job
    container_name: create_job
    network_mode: "host"
    environment:
       - ZEEBE_BROKER_ADDRESS
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "10"
  start_job:
    image: sitapati/zb-start_job
    container_name: start_job
    network_mode: "host"
    environment:
       - ZEEBE_BROKER_ADDRESS
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "10"
