# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 400d3e8a-fa00-11e8-8131-000d3ae13a31

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 400d3e8a-fa00-11e8-8131-000d3ae13a31
      ME_CONFIG_BASICAUTH_USERNAME: d6275c76-fa18-11e8-8185-000d3ae13a31
      ME_CONFIG_BASICAUTH_PASSWORD: dc41e2a2-fa18-11e8-b807-000d3ae13a31